cmake_minimum_required(VERSION 3.25 FATAL_ERROR)

project(mat91lib LANGUAGES C)

add_subdirectory(sam4s)
include(cmake/common.cmake)
add_subdirectory(ac EXCLUDE_FROM_ALL)
add_subdirectory(adc EXCLUDE_FROM_ALL)
add_subdirectory(cadc EXCLUDE_FROM_ALL)
add_subdirectory(dac EXCLUDE_FROM_ALL)
add_subdirectory(extint EXCLUDE_FROM_ALL)
add_subdirectory(pdc EXCLUDE_FROM_ALL)
add_subdirectory(pwm EXCLUDE_FROM_ALL)
add_subdirectory(spi EXCLUDE_FROM_ALL)
add_subdirectory(ssc EXCLUDE_FROM_ALL)
add_subdirectory(tc EXCLUDE_FROM_ALL)
add_subdirectory(twi EXCLUDE_FROM_ALL)
add_subdirectory(uart EXCLUDE_FROM_ALL)
add_subdirectory(udp EXCLUDE_FROM_ALL)
add_subdirectory(usart EXCLUDE_FROM_ALL)
