macro(get_mcu_family MCU DEST)
    if(MCU MATCHES "^SAM4S")
        set(${DEST} "SAM4S")
    elseif(MCU MATCHES "^SAM7")
        set(${DEST} "SAM7")
        message(SEND_ERROR "CMake support for SAM7 not implemented :(")
    else()
        message(FATAL_ERROR "Unknown MCU family for MCU '${MCU}'")
    endif()
endmacro()
